"""Part 4's Jev judge: the frozen prompt, the cache and budget, and the publication rule.

Every test runs offline: a fake transport answers in place of TypeSafe.
"""

import hashlib
import json
import ssl
from collections.abc import Callable
from datetime import UTC, date, datetime
from pathlib import Path

import pytest
from pydantic import SecretStr
from test_collect import scripted_cli
from test_pipeline import AI_ACT, LATER, RARE, collected, matching_world

from influence import cli
from influence.schemas.atlas import Amendment, ArticleVersion, Ask, LinkAssessment, SourceSpan
from influence.services import jev, jev_judge, pipeline

PROCEDURE = "2021/0106(COD)"
DOCUMENT = "doc:hys_attachment:paper"
PROPOSAL = (
    "Providers of high-risk AI systems shall keep the logs automatically generated by "
    "their systems for an appropriate period."
)
SOURCE = (
    "Background. We have read the proposal carefully. "
    "We ask that providers keep the logs for at least six months after placing on the "
    "market. Thank you."
)
SUPPORTING = {
    "actual_request": 0.9,
    "same_legal_change": 0.8,
    "incompatible_legal_change": 0.1,
    "shared_background": 0.2,
}
# PR #63's four `legal-change-v1` questions. The 0.67 cutoff was measured on Jev's answers
# to exactly these words, so any edit to them must fail here and be re-measured.
QUESTIONS_SHA256 = "d3498ab7988ba467aa43e4dbfc769b88cda801dc883442708a2d379e7ae259fe"


REQUEST = "We ask that providers keep the logs for at least six months after placing on the market."


def _ask(text: str = REQUEST, source: str = SOURCE) -> Ask:
    start = source.index(text)
    return Ask(
        ask_id="ask:paper-1",
        procedure_id=PROCEDURE,
        actor_id="actor:name:acme",
        document_id=DOCUMENT,
        span=SourceSpan(record_id=DOCUMENT, start=start, end=start + len(text), text=text),
        submitted_at=datetime(2021, 8, 1, tzinfo=UTC),
        extraction_method="passage-v0",
    )


def _amendment(old: str | None = "Providers shall keep the logs.") -> Amendment:
    return Amendment(
        amendment_id="am:2021-0106-COD:ENVI:7",
        procedure_id=PROCEDURE,
        document_id="doc:parltrack:ep_amendments",
        stage="committee",
        tabled_on=date(2022, 1, 25),
        target_provision="Proposal for a regulation - Article 12 - paragraph 1",
        old_text=old,
        new_text="Providers shall keep the logs for at least six months.",
    )


def _link(
    status: str = "unconfirmed", when: str = "ask_first", **changes: object
) -> LinkAssessment:
    return LinkAssessment.model_validate(
        {
            "link_id": "link:paper-1:am-7",
            "procedure_id": PROCEDURE,
            "amendment_id": "am:2021-0106-COD:ENVI:7",
            "ask_id": "ask:paper-1",
            "status": status,
            "support_score": 0.4,
            "time_eligibility": when,
            "method": "lexical-rules",
            "method_revision": "rules-3",
            **changes,
        }
    )


class FakeJev:
    """Answers each request from `answer(state)`; raises for states `fail` selects."""

    def __init__(
        self,
        answer: Callable[[dict[str, object]], dict[str, float]] = lambda _: SUPPORTING,
        fail: Callable[[dict[str, object]], bool] = lambda _: False,
    ) -> None:
        self.answer, self.fail = answer, fail
        self.states: list[dict[str, object]] = []

    def __call__(
        self, body: bytes, api_key: SecretStr, timeout: float, context: ssl.SSLContext
    ) -> bytes:
        request = json.loads(body)
        state: dict[str, object] = request["state"]
        self.states.append(state)
        if self.fail(state):
            raise OSError("connection reset")
        return json.dumps(
            {
                "model": jev.MODEL,
                "answers": {
                    key: {"type": "noul", "noul": value}
                    for key, value in self.answer(state).items()
                },
                "usage": {"input_tokens": 1000, "output_tokens": 40},
            }
        ).encode()


def _judge(tmp_path: Path, fake: FakeJev, max_usd: float = 1.0) -> jev_judge.JevJudge:
    client = jev.JevClient(SecretStr("offline"), ssl.create_default_context(), transport=fake)
    return jev_judge.JevJudge(client=client, cache=tmp_path / "jev", max_usd=max_usd, workers=2)


# --- The request --------------------------------------------------------------------------


def test_the_request_is_pr63s_frozen_prompt_with_its_context_policy() -> None:
    ask = _ask()
    request = jev_judge.judge_request(
        ask, _amendment(), SOURCE, jev_judge.proposal_articles([("Article 12", PROPOSAL)])
    )

    assert request is not None
    questions = json.dumps(
        {key: q.model_dump(exclude_none=True) for key, q in request.questions.items()},
        ensure_ascii=False,
    )
    assert hashlib.sha256(questions.encode()).hexdigest() == QUESTIONS_SHA256
    assert request.state == {
        "submission_old": None,
        "submission_new": ask.span.text,
        "preceding_context": SOURCE[: ask.span.start],
        "following_context": SOURCE[ask.span.end :],
        "amendment_old": "Providers shall keep the logs.",
        "amendment_new": "Providers shall keep the logs for at least six months.",
        "proposal_text": PROPOSAL,
        "proposal_context_status": "exact_target_provision",
    }


def test_only_the_proposal_article_is_dropped_to_fit_the_byte_bound() -> None:
    huge = {"article 12": "x " * jev.MAX_REQUEST_BYTES}
    request = jev_judge.judge_request(_ask(), _amendment(), SOURCE, huge)
    assert request is not None
    assert isinstance(request.state, dict)
    assert request.state["proposal_text"] is None
    assert request.state["proposal_context_status"] == (
        "omitted_full_provision_exceeds_request_bound"
    )
    unmatched = jev_judge.judge_request(_ask(), _amendment(), SOURCE, {"article 3": PROPOSAL})
    assert unmatched is not None
    assert isinstance(unmatched.state, dict)
    assert unmatched.state["proposal_context_status"] == "unavailable_no_exact_provision"
    long_source = SOURCE + "y " * jev.MAX_REQUEST_BYTES
    too_long = _ask(long_source[50:], long_source)
    assert jev_judge.judge_request(too_long, _amendment(), long_source, {}) is None


# --- Calls, cache and budget -------------------------------------------------------------


def test_identical_requests_are_asked_once_then_served_from_cache(tmp_path: Path) -> None:
    fake = FakeJev()
    request = jev_judge.judge_request(_ask(), _amendment(), SOURCE, {})
    assert request is not None

    first = _judge(tmp_path, fake).run([request, request])
    second = _judge(tmp_path, fake).run([request])

    assert len(fake.states) == 1
    assert (first.asked, first.cached, second.asked, second.cached) == (1, 0, 0, 1)
    assert first.spent_usd == pytest.approx(1000 * jev_judge.PRICE_PER_TOKEN)
    (answers,) = second.answers.values()
    assert answers.support == pytest.approx(0.8)


def test_a_failed_call_is_reported_and_the_others_still_answer(tmp_path: Path) -> None:
    fake = FakeJev(fail=lambda state: "logs" in str(state["amendment_new"]))
    good = jev_judge.judge_request(_ask(), _amendment(None), SOURCE, {})
    other = _amendment().model_copy(update={"new_text": "Deployers shall inform users."})
    bad = jev_judge.judge_request(_ask(), _amendment(), SOURCE, {})
    fine = jev_judge.judge_request(_ask(), other, SOURCE, {})
    assert good is not None
    assert bad is not None
    assert fine is not None

    report = _judge(tmp_path, fake).run([good, bad, fine])

    assert len(report.answers) == 1
    assert len(report.failures) == 2
    assert all(reason.startswith("Jev call failed") for reason in report.failures.values())
    assert not (tmp_path / "jev").exists() or len(list((tmp_path / "jev").iterdir())) == 1


def test_a_malformed_cache_file_is_asked_again(tmp_path: Path) -> None:
    fake = FakeJev()
    request = jev_judge.judge_request(_ask(), _amendment(), SOURCE, {})
    assert request is not None
    key = hashlib.sha256(jev_judge.request_bytes(request)).hexdigest()
    (tmp_path / "jev").mkdir()
    (tmp_path / "jev" / f"{key}.json").write_text("{not json")

    report = _judge(tmp_path, fake).run([request])

    assert (report.asked, report.cached) == (1, 0)


def test_the_budget_stops_new_calls_before_the_worst_case_could_exceed_it(
    tmp_path: Path,
) -> None:
    fake = FakeJev()
    requests = [
        jev_judge.judge_request(
            _ask(), _amendment().model_copy(update={"new_text": f"Rule {n}."}), SOURCE, {}
        )
        for n in range(5)
    ]
    assert all(r is not None for r in requests)

    # Room for one batch of two worst-case calls; their actual cost then leaves too little.
    report = _judge(tmp_path, fake, max_usd=2 * jev_judge.RESERVE_USD + 1e-5).run(
        r for r in requests if r is not None
    )

    assert len(fake.states) == 2
    assert len(report.failures) == 3
    assert all("budget was reached" in reason for reason in report.failures.values())


def test_an_answer_missing_a_question_is_a_failure_not_a_score(tmp_path: Path) -> None:
    request = jev_judge.judge_request(_ask(), _amendment(), SOURCE, {})
    assert request is not None
    key = hashlib.sha256(jev_judge.request_bytes(request)).hexdigest()
    (tmp_path / "jev").mkdir()
    partial = jev.JevResult.model_validate(
        {
            "model": jev.MODEL,
            "answers": {"actual_request": {"type": "noul", "noul": 0.9}},
            "usage": {"input_tokens": 10, "output_tokens": 1},
        }
    )
    (tmp_path / "jev" / f"{key}.json").write_text(partial.model_dump_json())

    report = _judge(tmp_path, FakeJev()).run([request])

    assert report.answers == {}
    assert "no Noul value for same_legal_change" in report.failures[key]


# --- The publication rule ----------------------------------------------------------------


def _answers(**changes: float) -> jev_judge.JevAnswers:
    return jev_judge.JevAnswers(**{**SUPPORTING, **changes})


def test_a_supported_reworded_pair_is_published_with_both_quotations() -> None:
    link, verdict = jev_judge.judged_link(_link(), _ask(), _amendment(), _answers(), PROPOSAL)

    assert verdict == "published"
    assert (link.status, link.tier) == ("published", "reworded")
    assert link.support_score == pytest.approx(0.8)
    assert link.ask_spans == (_ask().span,)
    assert [span.text for span in link.amendment_spans] == ["for at least six months"]
    assert link.signals["jev_support"] == pytest.approx(0.8)
    assert link.method_revision == "rules-3+jev-legal-change-v1"
    assert "not proof of influence" in link.limitations[-1]


@pytest.mark.parametrize(
    ("answers", "status"),
    [
        ({"same_legal_change": 0.66}, "unconfirmed"),
        ({"actual_request": 0.5}, "unconfirmed"),
        ({"shared_background": 0.4}, "unconfirmed"),
        ({"incompatible_legal_change": 0.34}, "unconfirmed"),
    ],
)
def test_any_answer_below_the_cutoff_keeps_the_rules_status(
    answers: dict[str, float], status: str
) -> None:
    link, verdict = jev_judge.judged_link(
        _link(), _ask(), _amendment(), _answers(**answers), PROPOSAL
    )
    assert (link.status, verdict) == (status, "below_cutoff")
    assert "jev_support" in link.signals


def test_the_rules_still_block_a_late_ask_and_quoted_proposal_text() -> None:
    late, verdict = jev_judge.judged_link(
        _link(status="insufficient_evidence", when="amendment_first"),
        _ask(),
        _amendment(),
        _answers(),
        PROPOSAL,
    )
    assert (late.status, verdict) == ("unconfirmed", "below_cutoff")
    assert "not dated before the amendment" in late.limitations[-1]

    quoted_text = "shall keep the logs automatically generated by their systems"
    source = f"We note that providers {quoted_text}."
    start = source.index(quoted_text)
    quoting = _ask().model_copy(
        update={
            "span": SourceSpan(
                record_id=DOCUMENT, start=start, end=start + len(quoted_text), text=quoted_text
            )
        }
    )
    quoted, verdict = jev_judge.judged_link(_link(), quoting, _amendment(), _answers(), PROPOSAL)
    assert (quoted.status, verdict) == ("unconfirmed", "below_cutoff")
    assert "0% of the matched ask wording is not quoted proposal text" in quoted.limitations[-1]


def test_contradicted_and_unjudged_links_keep_their_status() -> None:
    contradicted, verdict = jev_judge.judged_link(
        _link(status="contradicted"), _ask(), _amendment(), _answers(), PROPOSAL
    )
    assert (contradicted.status, verdict) == ("contradicted", "kept")

    unjudged, verdict = jev_judge.judged_link(_link(), _ask(), _amendment(), None, PROPOSAL)
    assert (unjudged.status, verdict) == ("unconfirmed", "not_judged")
    assert "exceeds the request bound" in unjudged.limitations[-1]
    failed, _ = jev_judge.judged_link(
        _link(), _ask(), _amendment(), None, PROPOSAL, "Jev call failed: reset"
    )
    assert failed.limitations[-1] == "Jev call failed: reset"


def test_change_spans_cover_deletions_unknown_originals_and_no_change() -> None:
    deletion = _amendment("Providers shall keep the logs for ten years.").model_copy(
        update={"new_text": "Providers shall keep the logs."}
    )
    spans = jev_judge._change_spans(deletion)  # pyright: ignore[reportPrivateUsage]
    assert [(s.field, s.text) for s in spans] == [("old_text", "for ten years")]

    unknown = jev_judge._change_spans(_amendment(None))  # pyright: ignore[reportPrivateUsage]
    assert [s.text for s in unknown] == [_amendment(None).new_text]

    same = _amendment().model_copy(update={"old_text": _amendment().new_text})
    assert [s.text for s in jev_judge._change_spans(same)] == [same.new_text]  # pyright: ignore[reportPrivateUsage]


# --- On the live path ---------------------------------------------------------------------


def test_the_view_publishes_what_jev_supports_and_says_what_the_judge_did(
    tmp_path: Path,
) -> None:
    fake = FakeJev(
        answer=lambda state: (
            SUPPORTING
            if RARE in str(state["amendment_new"]) and RARE in str(state["submission_new"])
            else {**SUPPORTING, "same_legal_change": 0.1}
        )
    )
    world = collected(matching_world(tmp_path))

    view = pipeline.build_view(world, generated_at=LATER, judge=_judge(tmp_path, fake))

    published = [link for link in view.bundle.links if link.status == "published"]
    assert [link.amendment_id for link in published] == ["am:2021-0106-COD:ENVI:PE7-7"]
    assert published[0].method_revision.endswith("+jev-legal-change-v1")
    assert ("ECHOED_BY", published[0].link_id) in {
        (edge.relation, edge.link_id) for edge in view.snapshot.edges
    }
    (note,) = [text for text in view.limitations if text.startswith("Jev (")]
    assert "1 published at support >= 0.67" in note
    assert f"{len(fake.states)} asked" in note


def test_judge_links_skips_settled_links_and_reports_unjudgeable_pairs(tmp_path: Path) -> None:
    fake = FakeJev()
    long_source = SOURCE + " " + "y " * jev.MAX_REQUEST_BYTES
    long_ask = _ask(long_source[len(SOURCE) + 1 :], long_source).model_copy(
        update={"ask_id": "ask:long", "document_id": "doc:hys_attachment:long"}
    )
    links = (
        _link(status="contradicted"),
        _link().model_copy(update={"link_id": "link:open"}),
        _link().model_copy(update={"link_id": "link:long", "ask_id": "ask:long"}),
    )
    article = ArticleVersion.model_validate(
        {
            "article_id": "art:p12",
            "procedure_id": PROCEDURE,
            "document_id": "doc:cellar:proposal",
            "stage": "proposal",
            "provision": "Article 12",
            "kind": "article",
            "text": PROPOSAL,
        }
    )

    judged, note = jev_judge.judge_links(
        _judge(tmp_path, fake),
        links,
        {"am:2021-0106-COD:ENVI:7": _amendment()},
        {"ask:paper-1": _ask(), "ask:long": long_ask},
        {DOCUMENT: SOURCE, "doc:hys_attachment:long": long_source},
        [article],
    )

    assert [link.status for link in judged] == ["contradicted", "published", "unconfirmed"]
    assert judged[0] == links[0]
    assert "exceeds the request bound" in judged[2].limitations[-1]
    assert len(fake.states) == 1
    assert fake.states[0]["proposal_text"] == PROPOSAL
    assert "judged 2 pair(s) in 1 distinct request(s): 1 published" in note
    assert "1 not judged" in note


def test_the_atlas_command_needs_a_key_and_a_positive_budget_for_jev(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.delenv(cli.JEV_KEY_VARIABLE, raising=False)
    assert cli.main(["atlas", AI_ACT, "--data-root", str(tmp_path), "--jev"]) == 2
    assert cli.JEV_KEY_VARIABLE in capsys.readouterr().err

    monkeypatch.setenv(cli.JEV_KEY_VARIABLE, "offline")
    args = ["atlas", AI_ACT, "--data-root", str(tmp_path), "--jev", "--jev-max-usd", "0"]
    assert cli.main(args) == 2
    assert "positive amount" in capsys.readouterr().err


def test_the_atlas_command_hands_the_view_a_cached_jev_judge(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    scripted_cli(monkeypatch, matching_world(tmp_path))
    monkeypatch.setenv(cli.JEV_KEY_VARIABLE, "offline")
    real = pipeline.build_view
    judges: list[jev_judge.JevJudge | None] = []

    def offline(
        collected: pipeline.Collected,
        *,
        generated_at: datetime,
        judge: jev_judge.JevJudge | None = None,
    ) -> pipeline.AtlasView:
        judges.append(judge)
        return real(collected, generated_at=generated_at)

    monkeypatch.setattr(cli, "build_view", offline)
    args = ["atlas", AI_ACT, "--data-root", str(tmp_path), "--jev", "--jev-max-usd", "3"]

    assert cli.main(args) == 0
    (judge,) = judges
    assert judge is not None
    assert (judge.cache, judge.max_usd) == (tmp_path / "cache" / "jev", 3.0)
    assert "Atlas:" in capsys.readouterr().out
