"""Part 4's Jev judge: the frozen prompt, the cache and budget, and the publication rule.

Every test runs offline: a fake transport answers in place of TypeSafe.
"""

import hashlib
import json
import ssl
from collections.abc import Callable
from datetime import UTC, date, datetime
from pathlib import Path

import pytest
from pydantic import SecretStr

from influence.schemas.atlas import Amendment, Ask, SourceSpan
from influence.services import jev, jev_judge

PROCEDURE = "2021/0106(COD)"
DOCUMENT = "doc:hys_attachment:paper"
PROPOSAL = (
    "Providers of high-risk AI systems shall keep the logs automatically generated by "
    "their systems for an appropriate period."
)
SOURCE = (
    "Background. We have read the proposal carefully. "
    "We ask that providers keep the logs for at least six months after placing on the "
    "market. Thank you."
)
SUPPORTING = {
    "actual_request": 0.9,
    "same_legal_change": 0.8,
    "incompatible_legal_change": 0.1,
    "shared_background": 0.2,
}
# PR #63's four `legal-change-v1` questions. The 0.67 cutoff was measured on Jev's answers
# to exactly these words, so any edit to them must fail here and be re-measured.
QUESTIONS_SHA256 = "d3498ab7988ba467aa43e4dbfc769b88cda801dc883442708a2d379e7ae259fe"


REQUEST = "We ask that providers keep the logs for at least six months after placing on the market."


def _ask(text: str = REQUEST, source: str = SOURCE) -> Ask:
    start = source.index(text)
    return Ask(
        ask_id="ask:paper-1",
        procedure_id=PROCEDURE,
        actor_id="actor:name:acme",
        document_id=DOCUMENT,
        span=SourceSpan(record_id=DOCUMENT, start=start, end=start + len(text), text=text),
        submitted_at=datetime(2021, 8, 1, tzinfo=UTC),
        extraction_method="passage-v0",
    )


def _amendment(old: str | None = "Providers shall keep the logs.") -> Amendment:
    return Amendment(
        amendment_id="am:2021-0106-COD:ENVI:7",
        procedure_id=PROCEDURE,
        document_id="doc:parltrack:ep_amendments",
        stage="committee",
        tabled_on=date(2022, 1, 25),
        target_provision="Proposal for a regulation - Article 12 - paragraph 1",
        old_text=old,
        new_text="Providers shall keep the logs for at least six months.",
    )


class FakeJev:
    """Answers each request from `answer(state)`; raises for states `fail` selects."""

    def __init__(
        self,
        answer: Callable[[dict[str, object]], dict[str, float]] = lambda _: SUPPORTING,
        fail: Callable[[dict[str, object]], bool] = lambda _: False,
    ) -> None:
        self.answer, self.fail = answer, fail
        self.states: list[dict[str, object]] = []

    def __call__(
        self, body: bytes, api_key: SecretStr, timeout: float, context: ssl.SSLContext
    ) -> bytes:
        request = json.loads(body)
        state: dict[str, object] = request["state"]
        self.states.append(state)
        if self.fail(state):
            raise OSError("connection reset")
        return json.dumps(
            {
                "model": jev.MODEL,
                "answers": {
                    key: {"type": "noul", "noul": value}
                    for key, value in self.answer(state).items()
                },
                "usage": {"input_tokens": 1000, "output_tokens": 40},
            }
        ).encode()


def _judge(tmp_path: Path, fake: FakeJev, max_usd: float = 1.0) -> jev_judge.JevJudge:
    client = jev.JevClient(SecretStr("offline"), ssl.create_default_context(), transport=fake)
    return jev_judge.JevJudge(client=client, cache=tmp_path / "jev", max_usd=max_usd, workers=2)


# --- The request --------------------------------------------------------------------------


def test_the_request_is_pr63s_frozen_prompt_with_its_context_policy() -> None:
    ask = _ask()
    request = jev_judge.judge_request(
        ask, _amendment(), SOURCE, jev_judge.proposal_articles([("Article 12", PROPOSAL)])
    )

    assert request is not None
    questions = json.dumps(
        {key: q.model_dump(exclude_none=True) for key, q in request.questions.items()},
        ensure_ascii=False,
    )
    assert hashlib.sha256(questions.encode()).hexdigest() == QUESTIONS_SHA256
    assert request.state == {
        "submission_old": None,
        "submission_new": ask.span.text,
        "preceding_context": SOURCE[: ask.span.start],
        "following_context": SOURCE[ask.span.end :],
        "amendment_old": "Providers shall keep the logs.",
        "amendment_new": "Providers shall keep the logs for at least six months.",
        "proposal_text": PROPOSAL,
        "proposal_context_status": "exact_target_provision",
    }


def test_only_the_proposal_article_is_dropped_to_fit_the_byte_bound() -> None:
    huge = {"article 12": "x " * jev.MAX_REQUEST_BYTES}
    request = jev_judge.judge_request(_ask(), _amendment(), SOURCE, huge)
    assert request is not None
    assert isinstance(request.state, dict)
    assert request.state["proposal_text"] is None
    assert request.state["proposal_context_status"] == (
        "omitted_full_provision_exceeds_request_bound"
    )
    unmatched = jev_judge.judge_request(_ask(), _amendment(), SOURCE, {"article 3": PROPOSAL})
    assert unmatched is not None
    assert isinstance(unmatched.state, dict)
    assert unmatched.state["proposal_context_status"] == "unavailable_no_exact_provision"
    long_source = SOURCE + "y " * jev.MAX_REQUEST_BYTES
    too_long = _ask(long_source[50:], long_source)
    assert jev_judge.judge_request(too_long, _amendment(), long_source, {}) is None


# --- Calls, cache and budget -------------------------------------------------------------


def test_identical_requests_are_asked_once_then_served_from_cache(tmp_path: Path) -> None:
    fake = FakeJev()
    request = jev_judge.judge_request(_ask(), _amendment(), SOURCE, {})
    assert request is not None

    first = _judge(tmp_path, fake).run([request, request])
    second = _judge(tmp_path, fake).run([request])

    assert len(fake.states) == 1
    assert (first.asked, first.cached, second.asked, second.cached) == (1, 0, 0, 1)
    assert first.spent_usd == pytest.approx(1000 * jev_judge.PRICE_PER_TOKEN)
    (answers,) = second.answers.values()
    assert answers.support == pytest.approx(0.8)


def test_a_failed_call_is_reported_and_the_others_still_answer(tmp_path: Path) -> None:
    fake = FakeJev(fail=lambda state: "logs" in str(state["amendment_new"]))
    good = jev_judge.judge_request(_ask(), _amendment(None), SOURCE, {})
    other = _amendment().model_copy(update={"new_text": "Deployers shall inform users."})
    bad = jev_judge.judge_request(_ask(), _amendment(), SOURCE, {})
    fine = jev_judge.judge_request(_ask(), other, SOURCE, {})
    assert good is not None
    assert bad is not None
    assert fine is not None

    report = _judge(tmp_path, fake).run([good, bad, fine])

    assert len(report.answers) == 1
    assert len(report.failures) == 2
    assert all(reason.startswith("Jev call failed") for reason in report.failures.values())
    assert not (tmp_path / "jev").exists() or len(list((tmp_path / "jev").iterdir())) == 1


def test_a_malformed_cache_file_is_asked_again(tmp_path: Path) -> None:
    fake = FakeJev()
    request = jev_judge.judge_request(_ask(), _amendment(), SOURCE, {})
    assert request is not None
    key = hashlib.sha256(jev_judge.request_bytes(request)).hexdigest()
    (tmp_path / "jev").mkdir()
    (tmp_path / "jev" / f"{key}.json").write_text("{not json")

    report = _judge(tmp_path, fake).run([request])

    assert (report.asked, report.cached) == (1, 0)


def test_the_budget_stops_new_calls_before_the_worst_case_could_exceed_it(
    tmp_path: Path,
) -> None:
    fake = FakeJev()
    requests = [
        jev_judge.judge_request(
            _ask(), _amendment().model_copy(update={"new_text": f"Rule {n}."}), SOURCE, {}
        )
        for n in range(5)
    ]
    assert all(r is not None for r in requests)

    # Room for one batch of two worst-case calls; their actual cost then leaves too little.
    report = _judge(tmp_path, fake, max_usd=2 * jev_judge.RESERVE_USD + 1e-5).run(
        r for r in requests if r is not None
    )

    assert len(fake.states) == 2
    assert len(report.failures) == 3
    assert all("budget was reached" in reason for reason in report.failures.values())


def test_an_answer_missing_a_question_is_a_failure_not_a_score(tmp_path: Path) -> None:
    request = jev_judge.judge_request(_ask(), _amendment(), SOURCE, {})
    assert request is not None
    key = hashlib.sha256(jev_judge.request_bytes(request)).hexdigest()
    (tmp_path / "jev").mkdir()
    partial = jev.JevResult.model_validate(
        {
            "model": jev.MODEL,
            "answers": {"actual_request": {"type": "noul", "noul": 0.9}},
            "usage": {"input_tokens": 10, "output_tokens": 1},
        }
    )
    (tmp_path / "jev" / f"{key}.json").write_text(partial.model_dump_json())

    report = _judge(tmp_path, FakeJev()).run([request])

    assert report.answers == {}
    assert "no Noul value for same_legal_change" in report.failures[key]
